# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "bw-tf-state-prod-us-east-2"
    dynamodb_table = "bw-tf-locks-prod"
    encrypt        = true
    key            = "prod/us-east-2/apigw/terraform.tfstate"
    region         = "us-east-2"
  }
}
