# Generated by Claude on 2025-08-12 for: DNS subzone delegation - dev.brainsway.cloud
# Creates hosted zone: dev.brainsway.cloud (in DEV account)

include "root" {
  path = find_in_parent_folders()
}

terraform {
  source = "../../../../modules/route53/subzone"
}

locals {
  environment = "dev"
}

inputs = {
  domain_name = "dev.brainsway.cloud"
  environment = local.environment

  # Keep low TTLs during rollout for fast flips
  ttl = 300

  tags = {
    Environment = local.environment
    ManagedBy   = "Terragrunt"
    Service     = "dns-subzone"
  }
}