# Generated by Claude on 2025-08-13 for: Lambda Test Runner function deployment

include "root" { path = find_in_parent_folders() }
terraform { source = "../../../../modules/lambda" }

locals {
  env_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))
  environment = local.env_vars.locals.env
  aws_account = local.env_vars.locals.aws_account
  aws_region = local.env_vars.locals.aws_region
}

inputs = {
  functions = {
    "lambda-test-runner" = {
      role        = "arn:aws:iam::574210586915:role/lambda-test-runner-role"
      handler     = "lambda_function.lambda_handler"
      runtime     = "python3.11"
      timeout     = 300  # 5 minutes for test execution
      memory_size = 1024 # 1GB for test execution
      
      architectures = ["x86_64"]
      
      # Environment variables for the Lambda Test Runner
      environment = {
        ENVIRONMENT           = local.environment
        TEST_S3_BUCKET       = "bw-lambda-test-reports-staging"
        LAMBDA_TEST_ENV      = "staging"
        LOG_LEVEL           = "INFO"
        PYTHONPATH          = "/opt/python:/var/runtime:/var/lang/lib/python3.11/site-packages"
      }
      
      # Use the packaged source code with dependencies
      source_dir = "/Users/motty/code/brainsway-infra/infra/lambda-functions/lambda-test-runner/package"
      
      tags = {
        Environment = local.environment
        Purpose     = "Lambda Test Runner - API-invokable testing system"
        ManagedBy   = "Terraform"
        Owner       = "Brainsway"
      }
    }
  }
  
  # Enable function URL for API Gateway-like access
  function_urls = ["lambda-test-runner"]
}