# Generated by Claude on 2025-08-13 for: Lambda Test Runner - DynamoDB tables for test history and dashboard

include "root" { path = find_in_parent_folders() }
terraform { source = "../../../../modules/dynamodb" }

locals {
  env_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))
  environment = local.env_vars.locals.env
  aws_account = local.env_vars.locals.aws_account
  aws_region = local.env_vars.locals.aws_region
}

inputs = {
  tables = {
    # Test execution history table
    "lambda-test-executions-${local.environment}" = {
      hash_key = "execution_id"
      range_key = "timestamp"
      
      attributes = {
        execution_id  = "S"
        timestamp     = "S"
      }
      
      # TTL for automatic cleanup (90 days)
      ttl_attribute = "ttl"
      ttl_enabled   = true
      
      billing_mode = "PAY_PER_REQUEST"
      
      tags = {
        Environment = local.environment
        Purpose     = "Lambda Test Runner - Execution History"
        ManagedBy   = "Terraform"
      }
    }
    
    # Test metrics and performance data
    "lambda-test-metrics-${local.environment}" = {
      hash_key = "metric_date"
      range_key = "metric_key"
      
      attributes = {
        metric_date = "S"  # Format: YYYY-MM-DD
        metric_key  = "S"  # Format: function_name#metric_type
      }
      
      # TTL for automatic cleanup (1 year)
      ttl_attribute = "ttl"
      ttl_enabled   = true
      
      billing_mode = "PAY_PER_REQUEST"
      
      tags = {
        Environment = local.environment
        Purpose     = "Lambda Test Runner - Performance Metrics"
        ManagedBy   = "Terraform"
      }
    }
    
    # Dashboard configuration and settings
    "lambda-test-dashboard-config-${local.environment}" = {
      hash_key = "config_type"
      
      attributes = {
        config_type = "S"  # dashboard_settings, alert_thresholds, etc.
      }
      
      billing_mode = "PAY_PER_REQUEST"
      
      tags = {
        Environment = local.environment
        Purpose     = "Lambda Test Runner - Dashboard Configuration"
        ManagedBy   = "Terraform"
      }
    }
  }
}