# Generated by Claude on 2025-08-14 for: Presigned URL S3 Upload Lambda Function
import json
import os
import boto3
import logging

logger = logging.getLogger()
logger.setLevel(logging.INFO)

s3_client = boto3.client('s3')
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'dev')

def lambda_handler(event, context):
    logger.info(f"Presigned URL S3 Upload Handler - Event: {json.dumps(event, default=str)}")
    
    try:
        # Handle test mode
        if isinstance(event, dict) and event.get('test', False):
            return {
                'statusCode': 200,
                'headers': {'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*'},
                'body': json.dumps({
                    'success': True,
                    'message': 'Test mode - presigned-url-s3-upload function',
                    'environment': ENVIRONMENT,
                    'function': 'presigned-url-s3-upload'
                })
            }
        
        return {
            'statusCode': 200,
            'headers': {'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*'},
            'body': json.dumps({
                'success': True,
                'message': 'Presigned URL S3 upload function is working',
                'environment': ENVIRONMENT,
                'function': 'presigned-url-s3-upload'
            })
        }
        
    except Exception as e:
        logger.error(f"Error: {str(e)}")
        return {
            'statusCode': 500,
            'headers': {'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*'},
            'body': json.dumps({'success': False, 'error': str(e), 'environment': ENVIRONMENT})
        }