repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.5
    hooks:
      - id: terraform_fmt
      - id: terragrunt_fmt
      - id: terraform_validate
      - id: tflint