# Generated by Claude on 2025-08-12 for: DNS delegation from prod to staging account
# In PROD account: delegates staging.brainsway.cloud to STAGING account name servers

include "root" {
  path = find_in_parent_folders()
}

terraform {
  source = "../../../../modules/route53/delegate_subzone"
}

# Pull the NS from the STAGING subzone remote state
dependency "staging_subzone" {
  config_path = "../../../../staging/us-east-2/apigw-http/route53"

  mock_outputs = {
    zone_id      = "ZMOCKSTAGING123456"
    name_servers = [
      "ns-234.awsdns-23.com.",
      "ns-567.awsdns-56.net.",
      "ns-890.awsdns-89.org.",
      "ns-345.awsdns-34.co.uk."
    ]
    domain_name = "staging.brainsway.cloud"
  }
}

locals {
  environment     = "prod"
  parent_zone_id  = "PARENT_ZONE_ID"  # <<<<<<<<<< REPLACE with brainsway.cloud Zone ID in PROD
}

inputs = {
  parent_zone_id         = local.parent_zone_id
  subdomain_name         = "staging.brainsway.cloud"
  subdomain_name_servers = dependency.staging_subzone.outputs.name_servers

  ttl = 300

  enable_delegation_validation  = true
  enable_delegation_monitoring  = true

  tags = {
    Environment   = local.environment
    ManagedBy     = "Terragrunt"
    Service       = "dns-delegation"
    TargetAccount = "574210586915" # STAGING account ID
  }
}