# Generated by Claude on 2025-08-12 for: DNS delegation from prod to staging account
# In PROD account: delegates staging.brainsway.cloud to STAGING account name servers

include "root" {
  path = find_in_parent_folders()
}

terraform {
  source = "../../../../../modules/route53/delegate_subzone"
}

# NOTE: Staging subzone dependency disabled for initial deployment
# Cross-account state access causes 403 Forbidden errors during initial setup
# Will re-enable after staging zone is created and accessible
#
# dependency "staging_subzone" {
#   config_path = "../../../../staging/us-east-2/apigw-http/route53"
#   mock_outputs = {
#     zone_id      = "ZMOCKSTAGING123456"
#     name_servers = [
#       "ns-234.awsdns-23.com.",
#       "ns-567.awsdns-56.net.",
#       "ns-890.awsdns-89.org.",
#       "ns-345.awsdns-34.co.uk."
#     ]
#     domain_name = "staging.brainsway.cloud"
#   }
# }

locals {
  environment      = "prod"
  parent_zone_id   = "Z0391113OQXSRY8SUJ92"  # Use specific zone ID from parent zone deployment
  parent_domain_name = "brainsway.cloud"
  
  # Real NS records from staging zone deployment (Zone ID: Z104771829W884YRWP0F1)
  # Updated with actual AWS DNS servers after staging zone creation
  staging_real_ns = [
    "ns-1505.awsdns-60.org.",
    "ns-1865.awsdns-41.co.uk.",
    "ns-378.awsdns-47.com.",
    "ns-535.awsdns-02.net."
  ]
}

inputs = {
  environment            = local.environment  # Required by delegate_subzone module
  parent_zone_id         = local.parent_zone_id  # Use specific zone ID instead of domain lookup
  subdomain_name         = "staging.brainsway.cloud"
  subdomain_name_servers = local.staging_real_ns  # Using real NS from staging zone deployment

  ttl = 300

  enable_delegation_validation  = true
  enable_delegation_monitoring  = true

  tags = {
    Environment   = local.environment
    ManagedBy     = "Terragrunt"
    Service       = "dns-delegation"
    TargetAccount = "574210586915" # STAGING account ID
  }
}