# Generated by Claude on 2025-08-12 for: DNS delegation from prod to staging account
# In PROD account: delegates staging.brainsway.cloud to STAGING account name servers

include "root" {
  path = find_in_parent_folders()
}

terraform {
  source = "../../../../modules/route53/delegate_subzone"
}

# NOTE: Staging subzone dependency disabled for initial deployment
# Cross-account state access causes 403 Forbidden errors during initial setup
# Will re-enable after staging zone is created and accessible
#
# dependency "staging_subzone" {
#   config_path = "../../../../staging/us-east-2/apigw-http/route53"
#   mock_outputs = {
#     zone_id      = "ZMOCKSTAGING123456"
#     name_servers = [
#       "ns-234.awsdns-23.com.",
#       "ns-567.awsdns-56.net.",
#       "ns-890.awsdns-89.org.",
#       "ns-345.awsdns-34.co.uk."
#     ]
#     domain_name = "staging.brainsway.cloud"
#   }
# }

locals {
  environment        = "prod"
  parent_domain_name = "brainsway.cloud"  # Will lookup zone ID dynamically
  
  # Static NS records for initial deployment (will be replaced with real ones later)
  # These are placeholder AWS DNS servers that will be replaced when staging zone is created
  staging_static_ns = [
    "ns-234.awsdns-23.com.",
    "ns-567.awsdns-56.net.",
    "ns-890.awsdns-89.org.", 
    "ns-345.awsdns-34.co.uk."
  ]
}

inputs = {
  parent_domain_name     = local.parent_domain_name  # Module will lookup zone ID
  subdomain_name         = "staging.brainsway.cloud"
  subdomain_name_servers = local.staging_static_ns  # Using static NS for initial deployment

  ttl = 300

  enable_delegation_validation  = true
  enable_delegation_monitoring  = true

  tags = {
    Environment   = local.environment
    ManagedBy     = "Terragrunt"
    Service       = "dns-delegation"
    TargetAccount = "574210586915" # STAGING account ID
  }
}