# Generated by Claude on 2025-08-12 for: DNS subzone delegation - staging.brainsway.cloud
# Creates hosted zone: staging.brainsway.cloud (in STAGING account)

include "root" {
  path = find_in_parent_folders()
}

terraform {
  source = "../../../../modules/route53/subzone"
}

locals {
  environment = "staging"
}

inputs = {
  domain_name = "staging.brainsway.cloud"
  environment = local.environment
  ttl         = 300

  tags = {
    Environment = local.environment
    ManagedBy   = "Terragrunt"
    Service     = "dns-subzone"
  }
}