# Generated by Claude on 2025-08-12 for: DNS delegation from prod to dev account
# In PROD account: delegates dev.brainsway.cloud to DEV account name servers

include "root" {
  path = find_in_parent_folders()
}

terraform {
  source = "../../../../modules/route53/delegate_subzone"
}

# Pull the NS from the DEV subzone remote state
dependency "dev_subzone" {
  config_path = "../../../../dev/us-east-2/apigw-http/route53"

  # Optional mocks for 'plan' when remote state not yet available
  mock_outputs = {
    zone_id      = "ZMOCKDEV123456"
    name_servers = [
      "ns-123.awsdns-12.com.",
      "ns-456.awsdns-45.net.",
      "ns-789.awsdns-78.org.",
      "ns-012.awsdns-01.co.uk."
    ]
    domain_name = "dev.brainsway.cloud"
  }
}

locals {
  environment     = "prod"
  parent_zone_id  = "PARENT_ZONE_ID"  # <<<<<<<<<< REPLACE with brainsway.cloud Zone ID in PROD
}

inputs = {
  parent_zone_id         = local.parent_zone_id
  subdomain_name         = "dev.brainsway.cloud"
  subdomain_name_servers = dependency.dev_subzone.outputs.name_servers

  ttl = 300

  # Optional validation/monitoring flags if your module supports them
  enable_delegation_validation  = true
  enable_delegation_monitoring  = true

  tags = {
    Environment   = local.environment
    ManagedBy     = "Terragrunt"
    Service       = "dns-delegation"
    TargetAccount = "824357028182" # DEV account ID
  }
}