# Generated by Claude on 2025-08-12 for: DNS delegation from prod to dev account
# In PROD account: delegates dev.brainsway.cloud to DEV account name servers

include "root" {
  path = find_in_parent_folders()
}

terraform {
  source = "../../../../../modules/route53/delegate_subzone"
}

# NOTE: Dev subzone dependency disabled for initial deployment
# Cross-account state access causes 403 Forbidden errors during initial setup
# Will re-enable after dev zone is created and accessible
#
# dependency "dev_subzone" {
#   config_path = "../../../../dev/us-east-2/apigw-http/route53"
#   mock_outputs = {
#     zone_id      = "ZMOCKDEV123456"
#     name_servers = [
#       "ns-123.awsdns-12.com.",
#       "ns-456.awsdns-45.net.",
#       "ns-789.awsdns-78.org.",
#       "ns-012.awsdns-01.co.uk."
#     ]
#     domain_name = "dev.brainsway.cloud"
#   }
# }

locals {
  environment      = "prod"
  parent_zone_id   = "Z0391113OQXSRY8SUJ92"  # Use specific zone ID from parent zone deployment
  parent_domain_name = "brainsway.cloud"
  
  # Static NS records for initial deployment (will be replaced with real ones later)
  # These are placeholder AWS DNS servers that will be replaced when dev zone is created
  dev_static_ns = [
    "ns-123.awsdns-12.com.",
    "ns-456.awsdns-45.net.", 
    "ns-789.awsdns-78.org.",
    "ns-012.awsdns-01.co.uk."
  ]
}

inputs = {
  environment            = local.environment  # Required by delegate_subzone module
  parent_zone_id         = local.parent_zone_id  # Use specific zone ID instead of domain lookup
  subdomain_name         = "dev.brainsway.cloud"
  subdomain_name_servers = local.dev_static_ns  # Using static NS for initial deployment

  ttl = 300

  # Optional validation/monitoring flags if your module supports them
  enable_delegation_validation  = true
  enable_delegation_monitoring  = true

  tags = {
    Environment   = local.environment
    ManagedBy     = "Terragrunt"
    Service       = "dns-delegation"
    TargetAccount = "824357028182" # DEV account ID
  }
}