# Generated by Claude on 2025-08-13 for: Lambda Test Runner IAM Role

include "root" { path = find_in_parent_folders() }
terraform { source = "../../../../modules/iam" }

locals {
  env_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))
  environment = local.env_vars.locals.env
  aws_account = local.env_vars.locals.aws_account
  aws_region = local.env_vars.locals.aws_region
}

inputs = {
  # Create Lambda Test Runner Role using the updated IAM module
  create_lambda_test_runner_role = true
  
  tags = {
    Environment = local.environment
    Purpose     = "Lambda Test Runner IAM Role"
    ManagedBy   = "Terraform"
  }
}