# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "bw-tf-state-staging-us-east-2"
    dynamodb_table = "bw-tf-locks-staging"
    encrypt        = true
    key            = "staging/us-east-2/s3/terraform.tfstate"
    region         = "us-east-2"
  }
}
