# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "bw-tf-state-dev-us-east-2"
    dynamodb_table = "bw-tf-locks-dev"
    encrypt        = true
    key            = "dev/us-east-2/rds/terraform.tfstate"
    region         = "us-east-2"
  }
}
