name: Test Minimal Workflow

on:
  push:
    branches: [feat/infrastructure-cleanup-enhancement]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Basic Execution
        run: echo "✅ Basic GitHub Actions execution works"